### ISSUE TITLE
Add to 7.2.2 or similar that using communities to signal validation status is a bad idea

### ISSUE THREAD

**Issue by ichdasich** [ichdasich/draft-ietf-grow-bgpopsecupd#7]
appending a community to signal the validation status of a prefix is generally considered a bad idea

**Comment by job** [comment]
Yes.

I have plans to specifically address this issue in a new internet-draft
“Associating validation states with BGP communities considered harmful”.

I think it’s worth spending a few pages on this on *why* exactly it’s a bad
idea. Perhaps useful to refer to that to-be-written doc instead of pulling
in walls of text?

**Comment by ichdasich** [comment]
Makes sense; Will keep an eye out for the draft and use a template reference until it is out.

**Comment by ichdasich** [comment]
Closed; Now recommending filtering outbound when using those (due to an ongoing migration away from them).

**Comment by job** [comment]
Reference https://datatracker.ietf.org/doc/draft-spaghetti-sidrops-avoid-rpki-state-in-bgp/

**Comment by ichdasich** [comment]
Added
